# How SATOSA transforms SAML2 credentials (so-called “subject”, part
# of the “assertion”; and “attributes”, part of “attribute statement”;
# both signed)

# Which attributes go into the frontend-side attribute statement.
#
# Keys of this dict correspond to what SATOSA sends to the SP (iValua)
#
# Values are the corresponding names on to pick from the back-end side
# (Tequila), with a fallback order as the second-order values.
# (If we were federating several back-end IdPs, which we aren't, we
# could have several intermediate-level keys.)
#
# If the dict is empty, there are no attributes at all.

attributes:
  # This is the minimal map that simply forwards everything that
  # Tequila sends us (under its default configuration):
  edupersonuniqueid:
    saml: [eduPersonUniqueId]
  mail:
    saml: [mail]
  givenname:
    saml: [givenName]
  surname:
    saml: [sn]
  uid:
    saml: [uid]
