all:
  hosts:
    catalyse-test:
      openshift_namespace: catalyse-test
      ansible_connection: local
      ansible_python_interpreter: "{{ catiamsible_dir }}/ansible-deps-cache/bin/python3"
      inventory_environment: test
