satosa_image: satosa/satosa:v7.0.3

satosa_configmap_mountpoint: /opt/satosa/config
satosa_secrets_mountpoint: /opt/satosa/secrets

sativa_server_hostname: >-
  {{ "catalyse-login.epfl.ch" if inventory_environment == "prod"
  else "catalyse-login-test.epfl.ch"
  }}

sativa_tequila_server: >-
  {{ "tequila.epfl.ch" if inventory_environment == "prod"
  else "test-tequila.epfl.ch"
  }}

sativa_tequila_server_metadata_url: >-
  {{ "/metadata.tequila-IdP.xml" if inventory_environment == "prod"
  else "/metadata.test-tequila-IdP.xml"
  }}

_satosa_secrets_keybase_team: >-
  {{ "epfl_catalyse.iam.test" if inventory_environment == "test"
     else "epfl_catalyse.iam.prod" }}
_satosa_secrets_keybase_file: "/keybase/team/{{ _satosa_secrets_keybase_team }}/satosa.yml"
satosa_secrets: >
  {{ lookup( 'pipe', 'keybase fs read {{ _satosa_secrets_keybase_file }}')
  | from_yaml }}

sativa_deploy_name: >-
  {{ "sativa-prod" if inventory_environment == "prod"
  else "sativa-test"
  }}

websrv_api:
  url: >-
    {{ "https://websrv.epfl.ch/" if inventory_environment == "prod"
    else "https://test-websrv.epfl.ch/"
    }}
  name: catalyse
  caller: '000000'

# TODO: where does catalyse-test.epfl.ch fit in?
catalyse_hostname: >-
  {{ "catalyse-test-proj.epfl.ch" if inventory_environment == "test"
  else "catalyse-buyer.epfl.ch" }}
catalyse_api:
  url: "https://{{ catalyse_hostname }}/page.aspx/en/eai/api/"
