erm_image_name: erm-proxy
erm_git_uri: git@github.com:epfl-si/erm-proxy
erm_ssh_secret_key_path: /keybase/team/epfl_catalyse.iam/ssh-clone/
erm_docker_clone_credentials_path: /keybase/team/epfl_catalyse.iam/epflclonebot.yml
erm_proxy_service_name: erm-proxy

erm_environments:
  prod:
    - name: prod
      route_name: erm-test-prod  # I suppose we could change this...
      service_name: erm-proxy-prod
      deployment_config_name: erm-proxy-prod
      hostname: "catalyse-erm.epfl.ch"
  test: 
    - name: test
      route_name: erm-test
      service_name: erm-proxy-test
      deployment_config_name: erm-proxy-test
      hostname: "erm-test.epfl.ch"
    - name: dev
      route_name: erm-dev
      service_name: erm-proxy-dev
      deployment_config_name: erm-proxy-dev
      hostname: "erm-dev.epfl.ch"
