- tags: always
  include_vars: erm-reverse-proxy-vars.yml

- name: Services
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ item.service_name }}"
        namespace: "{{ openshift_namespace }}"
      spec:
        ports:
          - name: 8443-tcp
            port: 8443
            protocol: TCP
            targetPort: 8443
        selector:
          deploymentconfig: "{{ item.deployment_config_name }}"
  with_items: "{{ erm_environments[inventory_environment] }}"
  tags:
    - erm.services

- name: Routes
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ item.route_name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          epfl.ch/visibility: "{{ 'public' if inventory_environment == 'prod' else 'private' }}"
      spec:
        host: "{{ item.hostname }}"
        port:
          targetPort: 8443-tcp
        tls:
          termination: passthrough
        to:
          kind: Service
          name: "{{ item.service_name }}"
  with_items: "{{ erm_environments[inventory_environment] }}"
  tags:
    - erm.routes
