- tags: always
  include_vars: erm-reverse-proxy-vars.yml

- name: Routes
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ item.route_name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          epfl.ch/visibility: "{{ 'public' if inventory_environment == 'prod' else 'private' }}"
      spec:
        host: "{{ item.hostname }}"
        port:
          targetPort: 8443-tcp
        tls:
          termination: passthrough
        to:
          kind: Service
          name: "{{ item.service_name }}"
  with_items: "{{ erm_environments[inventory_environment] }}"
  tags:
    - erm.routes
