- include_tasks:
    file: erm-reverse-proxy-build.yml
    apply:
      tags: erm
  tags:
    - erm
    - erm.build
    - erm.rebuild

- include_tasks:
    file: erm-reverse-proxy-deploy.yml
    apply:
      tags: erm
  tags:
    - erm
    - erm.services
    - erm.routes
